themeum/tutor

- classes/Tools_V2.php
Fix: WordPress debug mode showing twice in the tools section
> TUTOR2-893

- classes/Utils.php
Example:
```php
$fromDate  = '2022-06-29 14:00:00';
$oldDate   = '2022-06-22 14:00:00';
get_human_readable_time( $fromDate ); //  4d 20h 27m 22s left
get_human_readable_time( $fromDate, null, false ); // 4d 20h 27m 22s 
get_human_readable_time( $oldDate, '%ad:%hh:%im' ); // 2d:22hr:27m ago
get_human_readable_time( $fromDate, '%ad' ); // 4d left
get_human_readable_time( $fromDate, '%ad', false ); // 4d
```
> method added: get_human_readable_time

- assets/react/course-builder/lesson.js
- classes/Assets.php
API url was static none ssl http, that was causing the issue
Now API URL will be http or https based on SSL
> Fix: Vimeo not fetching video duration on live platform

- templates/single/lesson/lesson_sidebar.php
Current user enrollment status is checked earlier in this file's top section with `$is_enrolled` variable. Another check inside topic loop will cost DB query `topic * n` times!
> Performance - reduced db query call inside topic loop

- templates/single/lesson/lesson_sidebar.php
`Course_List::is_public` method unnecessarily called ( `lesson * n` times ) inside the lesson loop
> Performance - is_public_course variable moved outside of the loop

- templates/single/assignment/content.php
Removed the `continue lesson` button from the very last phase of the assignment.
[Jira task link](https://ollyo.atlassian.net/browse/TUTOR-1692)
> [Fix] In assignment page (the last one) continue lesson button need to be removed 🦜

- v2-library/_src/js/passwordStrengthChecker.js
As a user > settings
Password Field
- Changed the password strength text from `Week` to `Weak`
Task link
https://ollyo.atlassian.net/browse/TUTOR-1694
> Wrong text on settings(frontend) page

- assets/react/admin-dashboard/segments/options.js
- assets/scss/admin-dashboard/_tutor-admin.scss
- views/options/field-types/checkbox_horizontal.php
- views/options/field-types/toggle_switch.php
In the PHP side settings definition just add this for `toggle_switch` type setting.
```php
'toggle_fields' => 'settings_key_1,settings_key_2'
```
> Tutor Settings: On toggle switch show hide dependent settings elements

- .gitignore
- gulpfile.js
- tests/bootstrap.php
Add a `.env` file in root of project then add this entry.
```
WP_TESTS_DIR=absolute-path-of/wordpress-tests-lib
```
> 🎉 Unit Test - local .env file support added

- includes/tutor-template-functions.php
- templates/single-content-loader.php
- Fixed the issue when Content Drip "Course content available sequentially" is enabled and the lesson is locked but it shows the button
- Hide 'Mark as Complete' button for Assignment & Quiz page on mobile view
Task link
https://ollyo.atlassian.net/browse/TUTOR-1699
Related PR on Tutor-Pro
https://github.com/themeum/tutor-pro/pull/126
> Fixed Content Drip "Course content available sequentially" not working on the mobile device

- classes/Utils.php
Added to utils method `cancel_course_enrol`
> Hook added for third-party

- templates/single/course/enrolled/announcements.php
The announcement publish date format is showing wrong if someone translating the tutor. I have modified the code now the translation will work in a proper format.
> Date formate showing wrong after translation

- classes/Course.php
- classes/Frontend.php
- classes/Quiz.php
- classes/User.php
- classes/Utils.php
- models/CourseModel.php
- templates/loop/course-continue.php
- templates/single/common/header.php
- templates/single/course/course-entry-box.php
✅  Course auto-complete on the lesson page
✅  Course auto-complete on course details page
✅  Course auto-complete when a quiz is manually reviewed by the admin or instructor
✅  Review Progress link generate
✅  Course auto-complete when an assignment is manually reviewed by the admin or instructor
https://github.com/themeum/tutor-pro/pull/332
> Course autocomplete now sync with frontend and backend actions and review progress link generate 

- classes/Ajax.php
- readme.txt
Previously when user enable or disable an specific addons, it's firing enable/disable hooks for each addons which killing performance and invoking unnecessary action.
> Refactor and performance improvement for addons lifecycle hook fire 

- classes/Course.php
`add_action( 'admin_menu', __CLASS__ . '::load_media_scripts' )`;
`add_action( 'init', __CLASS__ . '::load_media_scripts' );`
Two hooks were added to load media templates. I had to use the `admin_menu` hook since it loads earlier than the `admin_init` hook
> Fix: WP Media Templates not loading properly on the Course Builder

- helpers/HttpHelper.php
Added a reusable class through the WordPress API for handling HTTP requests. This class includes commonly used HTTP status codes, allowing for the easy transmission of HTTP status codes in a readable format.
```php
use Tutor\Helpers\HttpHelper;
use JsonResponse;
$req = HttpHelper::get( 'https://example.com/api/users' );
if ( $req->has_error() ) {
$this->json_response( $req->get_error_message(), null, HttpHelper::STATUS_INTERNAL_SERVER_ERROR );
}
$req->get_status_code();
$req->get_headers();
$req->get_body();
$req->get_json();
```
> New - HttpHelper class added

- helpers/ValidationHelper.php
```php
use Tutor\Helpers\ValidationHelper;
$rules = [
'name' => 'min_length:5',
'age'  => 'if_input|numeric',
];
$inputs = [
'name' => 'John doe',
];
// Success.
ValidationHelper::validate( $rules, $inputs );
$inputs = [
'name' => 'John doe',
'age'  => 'dummy'
];
// Fail. reason, If the age input exists, it must be numeric
ValidationHelper::validate( $rules, $inputs );
```
> Optional input validation checking added

- templates/single/lesson/content.php
Assignment page deprication warning message issue fixed
> Fix: Frontend assignment deprication warning message

- assets/react/v3/shared/components/fields/FormTopicPrerequisites.tsx
- assets/react/v3/shared/config/typography.ts
This commit improves the accessibility and user experience in the `FormTopicPrerequisites` component. It adds `title` attributes to the `span` elements displaying the post titles and group titles, providing tooltips with the full text when the titles are truncated. Additionally, it closes the dropdown menu after selecting an item to enhance the user experience.
> feat: Improve accessibility and user experience in FormTopicPrerequisites

- assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/shared/components/fields/FormWPEditor.tsx
- assets/react/v3/shared/components/modals/Modal.tsx
- assets/react/v3/shared/hooks/usePortalPopover.tsx
This commit updates `usePortalPopover` to fix scrolling and position and `Modal` component to handle the `zIndex` property. It replaces the usage of the `zIndex` constant from the `@Config/styles` module with the `configZIndex` constant. This change ensures consistent handling of the `zIndex` value throughout the component.
> chore: Update usePortalPopover and modal component zIndex handling

- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentAccordion.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGeneration.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGenerationContext.tsx
- assets/react/v3/entries/course-builder/components/course-basic/ContentDripSettings.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/hooks/useGenerateCourseContent.ts
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/services/course.ts
This pull request introduces a new feature where a "Stop Generation" button is added to the AI content generation modal. This allows users to cancel the content generation process whenever needed. 
Changes in this PR include:
- Refactoring to only reset course price fields if not dirty
- Fixing contentDripType fallback in the convertCourseDataToFormData function
- Adding useEffect for resetting form on successful course update
- Implementing the new "Stop Generation" button for content generation
These changes enhance the user experience and provide more control over the content generation process.
> ✨ feat: Stop Genration Button added to AI content generation modal

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/shared/config/config.ts
- classes/Course.php
Here is the pull request description based on the provided information:
Adds an option to enable redirect on course publish from the frontend course settings.
This change introduces a new setting in the course settings that allows users to enable a redirect when a course is published. This provides more flexibility for course creators to control the user experience after a course is published.
The key changes include:
- Added a new setting in the course settings to enable/disable the redirect on publish
- Implemented the logic to handle the redirect when the setting is enabled
- Updated the course publish workflow to respect the new setting
This feature will help improve the course publishing experience and give course creators more control over the user flow.
> 🔥 feat(course-settings): add option to enable redirect on course publish from frontend

- assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
- assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/components/layouts/Tracker.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/shared/atoms/ImageInput.tsx
- assets/react/v3/shared/atoms/WPEditor.tsx
- assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
- assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
Here is the pull request description:
This pull request adds a new `readonly` prop to the `FromAnswerExplantion` component and applies the necessary styles. The new prop allows the component to be displayed in a read-only mode, which is useful for scenarios where the user should not be able to edit the content.
The changes include:
- Added the `readonly` prop to the `FromAnswerExplantion` component
- Applied styles to the component to visually indicate the read-only state
These changes will improve the overall functionality and user experience of the `WPEditor` feature.
> ✨feat: add readonly prop FromAnswerExplantion and apply styles

- ecommerce/HooksHandler.php
Hook added
`do_action( 'tutor_order_enrolled', $order, $enrollment_id );`
> Fix - enrollment not cancelled on subscription cancelled

- ecommerce/CheckoutController.php
- includes/tutor-general-functions.php
- models/OrderModel.php
- templates/dashboard/purchase_history.php
- templates/ecommerce/order-placement-failed.php
The pay button will appear only if a user tries to make a payment and fails. Not applicable for the Manual Enrollment.
1. Now students will be able to make the payment for failed order
2. `tutor_redirect_after_payment` new function added
3. The purchase history table updated
4. **Back to checkout**  URL set using `wp_get_referer `
> Pay Option for The Failed Order

- classes/Utils.php
Reopen of #522 for @w3guy:
> Add `$sub_url` to `tutor_dashboard_url` filter
@w3guy said about this submission at https://github.com/themeum/tutor/pull/496#issuecomment-1661586546:
> _"This PR is important to us though"_:
>
> I am unable to create a PR against the dev branch. I don't have such permission.
> Here's my fork https://github.com/w3guy/tutor/commit/40bc7cc3b5c4ccbe0762e5cbf4c101881c595f59
> Added $sub_url to tutor_dashboard_url filter

- classes/WooCommerce.php
@shewa12, the problem that this change fixes is:
Even if WooCommerce Monetization is not used, when WooCommerce gets deactivated, Tutor LMS currently adds a permanent banner at the top of the admin dashboard which only gets cleared when WooCommerce gets re-activated.
The only trick to get around this right now is to deactivate tutor, then deactivate/uninstall WooCommerce, and the re-activate tutor again, and to get the idea for this trick, you have to study the source code deeply.
Fix:
The WooCommerce deactivation handler shall only act when monetize_by === 'wc':
- Fix: When the WooCommerce plugin gets deactivated, do not disable other possible monetization methods like Paid Memberships Pro (pmpro) or EDD.
- Fix: When the WooCommerce plugin gets deactivated, and WooCommerce was not …
> Fix WooCommerce deactivation handler

- assets/react/v3/entries/course-builder/components/course-basic/EnrollmentSettings.tsx
Conditionally render enrollment settings based on whether the membership-only mode is enabled. This change improves the user experience by hiding irrelevant options when the mode is active.
> Update enrollment settings for membership-only mode

- assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
Remove the FocusTrap component from both wrappers and streamline the header rendering for improved clarity and maintainability.
> Refactor ModalWrapper and BasicModalWrapper to simplify structure

- assets/react/v3/shared/services/subscription.ts
Update subscription service methods to use object_id instead of course_id for improved clarity and consistency.
> 🔧 Rename course_id to object_id in subscription service methods

- assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
- assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
- assets/react/v3/entries/course-builder/components/course-basic/CourseBasicSidebar.tsx
- assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicHeader.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/shared/components/subscription/OfferSalePrice.tsx
- assets/react/v3/shared/services/subscription.ts
Eliminate the `selectOnFocus` property from various form inputs to streamline the user experience and improve form behavior.
> 🛠️ Refactor: Remove selectOnFocus from form inputs

- assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
- assets/react/v3/entries/course-builder/components/fields/quiz/FormFillinTheBlanks.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
Ensure consistent string comparison for IDs in `QuizSettings`, `AssignmentModal`, and `LessonModal`. Update the condition for `edit mode` in `FormFillInTheBlanks` to improve functionality.
> 🔧 Fix string comparison for IDs in modals and refactor edit mode condition

- assets/react/v3/entries/course-builder/pages/Additional.tsx
- assets/react/v3/shared/services/course.ts
Update the course list parameters to use 'exclude' instead of 'excludedIds' for clarity and consistency.
> 🛠️ Rename excludedIds to exclude in course list parameters

- assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
- templates/single/quiz/parts/question.php
Eliminate 'ordering' from the supportRandomize question types to streamline the available options.
> 🛠️ Refactor supportRandomize question types by removing 'ordering'

- ecommerce/CouponController.php
Eliminate the coupon_type from the data before processing to streamline coupon handling.
> 🛠️ Prevent `coupon_type` from changing and validation added for specific_courses/bundles/categories type coupon

- assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
Update the logic for displaying membership plans in coupon discount options to ensure it aligns with the active subscription status.
> 🛠️ Fix membership plans logic in coupon discount options

- helpers/QueryHelper.php
Currently `QueryHelper::build_where_clause` only support `=`, and `IN` operator.
This PR resolves the previous limitation and adds support for all common SQL comparison operators.
```php
$where = array(
'id'         => ['BETWEEN', [10, 20]],
'status'     => ['!=', 'draft'],
'email'      => ['LIKE', '%@gmail.com'],
'type'       => ['NOT IN', ['test', 'sample']],
'age'        => ['>=', 18],
'active'     => true,
'deleted_at' => 'null',
'role'       => 'editor',
)
QueryHelper::build_where_clause( $where );
```
> 🎉  All common SQL comparison operators support added to QueryHelper

- assets/react/v3/entries/order-details/components/order/OrderItem.tsx
- assets/react/v3/entries/order-details/components/order/Payment.tsx
Implement net payment to handle the PaymentActionButton component and update relevant imports. This change ensures that the button does not render when the net payment is zero or less.
Single Purchase using 100% coupon
Subscription using 100% coupon
Membership with trial
> 💳 Add `net-payment` condition to handle PaymentActionButton

- classes/Admin.php
- classes/Announcements.php
- classes/Course_List.php
- classes/Course_Widget.php
- classes/Instructors_List.php
- classes/Quiz_Attempts_List.php
- classes/Students_List.php
- classes/Tutor.php
- classes/Withdraw_Requests_List.php
- ecommerce/CouponController.php
- ecommerce/OrderController.php
**Problem:**
WordPress _load_textdomain_just_in_time load the translation after the initialization of WP. When the translation functions like __, esc_html_e get called before loading the translation functions it throws error.
**Solution:**
Calling the translation functions after loading WP solved the issue. Used the `init` action hook. Thanks to the WP hooks. Below is an example of solution:
**Previous Code:**
`$this->page_title = __( 'Quiz Attempts', 'tutor' );`
**Current Code:**
```
add_action(
'init',
function() {
$this->page_title = __( 'Quiz Attempts', 'tutor' );
}
);
```
> Fixed The _load_textdomain_just_in_time Notice Error

- assets/react/v3/entries/course-builder/components/layouts/header/HeaderActions.tsx
Adjust the condition for dropdown visibility to display when there are available items instead of requiring more than one.
> 🔧 fix: update dropdown visibility condition to show when items are available

- assets/react/v3/shared/molecules/Table.tsx
Update the type of `renderInLastRow` to `ReactNode` for better flexibility and remove unnecessary borders from table styles for a cleaner appearance.
> ✨ fix: update renderInLastRow type and clean up table styles

- classes/Utils.php
- `can_user_edit_course()` was using the logic `current_user_can( 'edit_tutor_course', $course_id ) || $this->is_instructor_of_this_course( $user_id, $course_id );`
- this was allowing instructors to edit admins posts thus causing security issue
- since `current_user_can( 'edit_tutor_course', $course_id )` returns true for instructor as instructor role has this capability
> Fix: can user edit course check logic not correctly implement

- assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
Ensure the search functionality does not appear when the input is disabled, improving user experience and preventing unnecessary interactions.
> 🔧 Prevent search display when input is disabled

- helpers/QueryHelper.php
A wrapper method of global $wpdb to get last executed query.
> New: get last executed query method

- assets/react/v3/entries/tax-settings/components/TaxRates.tsx
- assets/react/v3/entries/tax-settings/services/tax.ts
Introduce an `enable_tax` field in the `TaxSettings` interface and update the `TaxRates` component to include a checkbox for enabling tax rates and calculations.
> ✨ feat: add enable_tax field to TaxSettings interface and update TaxRates component

- assets/react/v3/entries/tax-settings/components/App.tsx
- assets/react/v3/entries/tax-settings/components/TaxSettings.tsx
Introduce default values for `enable_tax` and `enable_individual_tax_control` in the `TaxSettingsPage` to enhance tax configuration options.
> ✨ feat: add default values for tax settings fields

- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Update the export modal to replace 'bundles' with 'course-bundle' for improved data management.
> 🛠️ fix: update export modal to use 'course-bundle' for data handling

- assets/react/v3/entries/import-export/components/modals/CourseListModal/index.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
Introduce an `onSelect` prop in the CourseListModal to handle course selection, enabling the ExportModal to respond to selected courses effectively.
> ✨ feat: add onSelect prop to CourseListModal for course selection handling in ExportModal

- assets/react/v3/entries/import-export/components/Import.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Eliminate unnecessary properties from the ExportFormData interface to streamline the codebase.
> 🧹 Refactor: Remove unused properties from ExportFormData interface

- assets/react/v3/shared/icons/types.ts
This solution uses the as const assertion, which tells TypeScript to treat the array as a readonly tuple with specific string literal values. When we then access typeof icons[number], TypeScript will correctly extract a union type of all the specific string literals in the array, rather than just inferring the type as string.
Now when you use IconCollection in your code, TypeScript will show it as a union of all the specific icon names, providing proper type checking and autocomplete for valid icon names.
> 🔧 Fix: update icons array to be a readonly tuple for TS suggestion

- assets/react/v3/shared/components/FocusTrap.tsx
- assets/react/v3/shared/components/fields/quiz/FormQuestionTitle.tsx
- assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
Add `blurPrevious` prop to `FocusTrap` for controlling previous element blurring. Update `FormQuestionTitle` ref handling for input elements. Introduce `blurTriggerElement` prop in `BasicModalWrapper` and `ModalWrapper` to manage `FocusTrap` behavior.
> ✨ feat: Enhance FocusTrap and Modal components with blur control props

- assets/react/v3/shared/atoms/Tooltip.tsx
Add a zIndex prop to the Tooltip component to enhance control over its layering in the UI.
> ✨ Refactor Tooltip to include zIndex prop for improved layering control

- classes/Utils.php
Added a condition to only include course ratings from comments with 'approved' status. This ensures that only approved reviews are considered in course rating calculations.
> Display only approved ratings in instructors profile

- assets/react/v3/shared/services/import-export.ts
- assets/react/v3/shared/utils/endpoints.ts
Rename the endpoint for clarity and update the context parameter to use an underscore instead of a hyphen.
> 🔧 Refactor endpoint name from SYNC_FROM_COURSES to IMPORT_FROM_COURSES

- assets/icons/course.svg
- assets/react/v3/shared/icons/types.ts
- classes/Icon.php
Introduced a new 'course' SVG icon, registered it in the TypeScript icon list and the Icon PHP class. This allows the course icon to be used throughout the application where icons are referenced.
> Add new course icon to icon set

- rspack.config.mjs
Disable caching in the base configuration to ensure fresh builds without stored data.
> 🔧 Disable caching in base configuration

- helpers/QueryHelper.php
We now have a simple and efficient `query()` method that supports every scenario with a variety of clauses, including:
- SELECT
- JOIN
- WHERE
- SEARCH
- GROUP BY
- HAVING
- ORDER BY
- PAGINATION
It can return a full result set, a single row, or just the count.
```php
$args = array();
$results = QueryHelper::query( 'posts', $args );
```
> New: query() method added to database query with flexible arguments.

- assets/react/v3/entries/import-export/components/modals/CollectionList/CollectionListTable.tsx
- assets/react/v3/shared/atoms/Button.tsx
- assets/react/v3/shared/components/FocusTrap.tsx
- stories/atoms/Button.stories.tsx
✨ New Features & Improvements
- Polymorphic Button/Anchor Support
- The Button can now render as either a `<button>` or an `<a>` element, controlled by the as prop. 
- When `as="a"`, the href prop is required and button-specific props are forbidden. 
- When as is not `"a"`, anchor-specific props are forbidden.
- TypeScript enforces these rules, preventing invalid prop combinations at compile time.
- Icon-Only Button Mode (isIconOnly)
- Added isIconOnly prop to render a button with only an icon, no children. 
- When isIconOnly is true, `children` is forbidden and `icon` is required (enforced by TypeScript).
- Requires an aria-label for accessibility in icon-only mode.
- Improved Accessibility
- Uses both `:disabled` and `[aria-disabled="true"]` selectors to ensure correct styling and …
> ✨ Enhance Button component with icon-only support and accessibility improvements

- templates/email/email_styles.php
Moved the :last-child selector for border-right removal to a separate CSS rule to ensure proper application. This improves the table's appearance by correctly removing the right border from the last cell.
> 🛠️ Fix CSS for last-child border in email datatable

- classes/Utils.php
This PR addresses the below issues and fixed.
1. Sequential array zero-index is not accessable.
```php
$arr = array( 100, 300, 400 );
avalue_dot( 0, $arr ); // output: false, it should be 100;
avalue_dot( 1, $arr ); //output: 300 (ok)
avalue_dot( 2, $arr ); //output: 400 (ok)
```
2. Non-array value casting as array and it makes non array value to array
```php
$v = 123;
$v = (array) $v; // output: [ 33 ];
avalue_dot( 0, $v ); // output: 33, it should be false
```
> Fixed multiple issues to `array_avalue_dot` helper
