- classes/Options.php
- classes/Utils.php
- templates/dashboard/dashboard.php
- templates/dashboard/earning.php
- templates/dashboard/earning/statement.php
- templates/dashboard/earning/statements.php
- templates/dashboard/enrolled-courses/active-courses.php
- templates/dashboard/my-quiz-attempts.php
- templates/dashboard/quiz-attempts.php
- templates/dashboard/settings/reset-password.php
- templates/dashboard/wishlist.php
Updated some texts on the Dashboard pages to make more sense.
> Text Update

- templates/single/lesson/required-enroll.php
Changed the place of the parenthesis to fix the translation.
> Update required-enroll.php - translation fix

- templates/dashboard/instructor/registration.php
- templates/dashboard/registration.php
Avoids form submit in modern browsers if the input fields are empty.
More info:
https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands
https://developer.mozilla.org/es/docs/Web/HTML/Atributos/autocomplete
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
> Updated input fields with required and autocomplete

- views/options/field-types/checkbox_horizontal.php
- views/options/field-types/toggle_switch.php
- views/options/template/color_picker.php
> Backend Setting will keep previous data from now

- assets/scss/front/course-spotlight/quiz.scss
- templates/single/quiz/parts/image-matching.php
- templates/single/quiz/parts/question.php
- v2-library/_src/scss/ui-components/_ui-course-details-elements.scss
[TUTOR2-647](https://ollyo.atlassian.net/browse/TUTOR2-647)
[TUTOR2-647](https://ollyo.atlassian.net/browse/TUTOR2-647)
> The matching type quiz has responsive issue, Placeholder Image of the Course is being shown Partially

- assets/scss/front/__archive.scss
- assets/scss/front/course-spotlight/spotlight.scss
- templates/dashboard/dashboard.php
- templates/global/attachments.php
- templates/single/course/course-entry-box.php
- templates/single/lesson/comment.php
- templates/single/lesson/content.php
[TUTOR2-669](https://ollyo.atlassian.net/browse/TUTOR2-669)
[TUTOR2-691](https://ollyo.atlassian.net/browse/TUTOR2-691)
[TUTOR2-746](https://ollyo.atlassian.net/browse/TUTOR2-746)
> The Lesson Container is sometimes being so Narrrow, Close icon spotlight lesson, on mobile, course progress enroll/expiration issue

- classes/Utils.php
count util functions added for pro report
> count util functions added for pro report

- classes/Admin.php
What I have doe
- Refactor with `phpcbf` for WordPress coding standard.
- Input class implemented where raw `$_GET` used.
- Simplified some code for enhancing code readability.
- Function block comment added
> Refactor and input class added

- classes/Shortcode.php
https://ollyo.atlassian.net/browse/TLAT-88
> Pages are creating infinite loop 

- classes/Course.php
- templates/dashboard/create-course.php
- Frontend course builder ( Discount price added)
- Course details track incomplete assignments also
> 1153 and 1175

- classes/Utils.php
- classes/Withdraw.php
- models/Withdraw.php
- templates/dashboard/dashboard.php
- templates/dashboard/settings/withdraw-settings.php
- templates/dashboard/withdraw.php
- views/pages/withdraw_requests.php
- Withdraw model added
- Removed withdraw-related methods into `withdraw` model
- Removed some redundant code
- Implement Minimum days before balance is available features
> Withdraw: Minimum Days Before Balance is Available

- assets/react/course-builder/course-price.js
- classes/Course.php
- classes/Utils.php
- classes/WooCommerce.php
- views/metabox/course-add-product-metabox.php
- views/metabox/product-selection.php
- views/quiz/attempt-table.php
- For free only dropdown
- For PRO auto product create, link product and update price
> WC product create or link from WP Admin

- classes/Utils.php
- models/Course.php
- Removed unused `get_course_count` from utils and add `count` method to the course model with status parameter.
- Removed unused methods from utils `get_publish_courses_by_instructor` , `get_pending_course_by_instructor ` and `get_archive_page_course_count `
> Refactor and removed unused methods

- classes/Course.php
- classes/Utils.php
- classes/Withdraw.php
- models/CourseModel.php
- models/WithdrawModel.php
- templates/dashboard/dashboard.php
- templates/dashboard/settings/withdraw-settings.php
- templates/dashboard/withdraw.php
- templates/single/common/header.php
- views/pages/withdraw_requests.php
- Model suffix added to each model for reducing miss-class invocation during development.
- Updated each places where model was called
> Model suffix added

- classes/Utils.php
- models/LessonModel.php
Remove unused methods from utils
```
get_lesson_count
get_lessons_by_topic
get_lesson_type_icon
```
Move to LessonModel
```
get_total_lesson
get_lesson_count_by_course
get_lesson_reading_info
get_lesson_reading_info_full
```
> Remove unused method and move utils method to model

- classes/Quiz.php
- classes/Utils.php
- models/QuizModel.php
Removed Unused Method
```    
get_quiz_id_by_question
```
Move to model
```
quiz_next_question_order_id
quiz_next_question_id
quiz_attempts
quiz_ended_attempts
get_quiz_question_by_id
```
> Move utils method to quiz model

- assets/scss/course-builder/modal/quiz.scss
- classes/Quiz.php
- models/QuizModel.php
- views/modal/edit_quiz.php
- views/quiz/attempt-details.php
> Quiz pass required for next content access

- templates/archive-course-init.php
- templates/course-embed.php
- templates/course-none.php
- templates/dashboard.php
- templates/feature_disabled.php
- templates/instructor-setting.php
- templates/login-form.php
- templates/login.php
- templates/permission-denied.php
- templates/public-profile.php
- templates/single-assignment.php
- templates/single-content-loader.php
- templates/single-course.php
- templates/single-lesson.php
- templates/single-preview-lesson.php
- templates/single-quiz.php
- templates/single/course/reviews.php
- templates/template.php
- Code formatting and indentation
- File comment
> Fix - code formatting and file comment

- classes/Announcements.php
- classes/Assets.php
- classes/Backend_Page_Trait.php
- classes/Course_Embed.php
- classes/Course_Filter.php
- Announcements class
- Assets class
- Backend Page Trait
- Course_Embed class
- Course_Filter class
> WPCS & security fixes from classes directory

- classes/Custom_Validation.php
- classes/Dashboard.php
- classes/FormHandler.php
- classes/Frontend.php
- classes/Gutenberg.php
- Custom validation trait
- Dashboard class
- FormHandler class
- Frontend class
- Gutenberg class
> WPCS and security fixes

- classes/Tutor_Setup.php
- classes/Utils.php
- classes/WooCommerce.php
WC order getting auto-completed even when the product not belong to Tutor
Student getting enrolled before payment completion
Setup wizard text update
> Fixes & Improvement

- classes/Utils.php
- models/CourseModel.php
- templates/dashboard/announcements.php
- templates/dashboard/assignments.php
- templates/dashboard/dashboard.php
- templates/dashboard/elements/filters.php
- templates/dashboard/my-courses.php
- templates/profile/courses_taken.php
- views/elements/filters.php
- views/fragments/announcement-list.php
- Removed `get_courses_by_instructor` method from `Utils` class to `CourseModel`
- Used that method from course model instead of Utils class.
> Moved `get_courses_by_instructor` util helper to course model

- templates/single-content-loader.php
`$course_id` already queried top of the file.
> Performance - removed unnecessary course id query

- classes/Utils.php
- `Fix` - `N` number of queries executed for quiz lesson.
- `Fix` - `N` number of queries executed for assignment lesson.
> Performance - reduced number of query to get course complete percentage 🎉 

- classes/Assets.php
- includes/tutor-template-functions.php
- templates/dashboard.php
- Template function refactoring & error handling
- Hooks added for extending Tutor
> Filter Hooks & Code Refactor

- assets/react/course-builder/lesson.js
- templates/single/assignment/content.php
There is no content on the lesson, but still it is showing overview section - Spotlight Mode
[JIRA card link](https://ollyo.atlassian.net/browse/TUTOR-1696)
> Fixed showing overview even there is no content in Spotlight Mode 🎉

- templates/single/assignment/content.php
Added missing logic for other content description issues.
> Fixed description issue

- readme.txt
> Updated changelog

- assets/react/v2/table-status.js
Reproduce the issue
- As an admin click on the instructor list page or any list page from the backend 
- Now change the status (ex. - approve/ cancel/ pending)
- observe that it is generating an error
Fixed the issue on `table-status.js` file
Jira link
https://ollyo.atlassian.net/browse/TUTOR-1447
> All listing page's status change null property issue fix (js)

- assets/scss/modules/qna.scss
Student to Instructor chat issue
- As a student ask questions using Bullet Points
- As an instructor check in the backend that the Bullet Point is not appearing
After Fixing  
Task Url
https://ollyo.atlassian.net/browse/TUTOR-1491
> Fix: In the backend Q&A page, List Item design was not appearing

- assets/scss/front/index.scss
- templates/dashboard/instructor/registration.php
- templates/dashboard/registration.php
- templates/login-form.php
Added Hooks:
```tutor_after_register_button```
```tutor_after_sign_in_button ```
> Custom Hooks added to extend Tutor

- helpers/SessionHelper.php
- tests/phpunit/SessionHelperTest.php
PHPUnit test result
Run the test case by the following command
`vendor/bin/phpunit --filter=SessionHelperTest`
To avoid PHPUnit error, use this at the beginning of `tutor/tests/bootstrap.php` file
```php
! session_id() ? session_start() : 0;
```
> 🎉 Session helper class added with PHPUnit test case

- classes/Utils.php
- includes/translate-text.php
Translation issues: Quiz attempt time issue fix
Jira task link
https://ollyo.atlassian.net/browse/TUTOR-1667
> Translate issue fix for frontend my quiz attemps time

- assets/scss/front/__archive.scss
- templates/dashboard/registration.php
Updated Register page to sync the look of the login page.
> Redesign register page

- assets/react/lib/tutor.js
- cache/FlashMessage.php
- classes/Instructor.php
- classes/Student.php
- includes/tutor-general-functions.php
The caching mechanism for flash message on top of `WP Transient`
Close-able alert message `tutor_close_able_alert_msg `
> Hooks to extend Tutor, reuse-able flash & alert message helpers 🎉 

- templates/dashboard/instructor/registration.php
Redesigned Instructor registration page.
> Instructor registration page redesigned 🎨

- assets/react/admin-dashboard/segments/import-export.js
On Tools page Deleting `Settings History` freezes vertical scrolling
Task Url
https://ollyo.atlassian.net/browse/TUTOR-1749
> On Tools page Deleting `Settings History` freezes vertical scrolling

- classes/Instructor.php
Related PR
https://github.com/themeum/tutor-pro/pull/156
> instructor construct register hook check added

- classes/Utils.php
What I'have done
- Restructured comment according to WPCS comment standard.
- Missing function comment added.
- Add parameter comments.
> WPCS fixes on entire Utils class.

- classes/User.php
Example
```php
use TUTOR\User;
User::is( User::ADMIN );
User::has_any_role( array( User::ADMIN, User::INSTRUCTOR ) );
User::is_admin( );
User::is_instructor( );
User::is_student( );
```
> User helper method added

- assets/react/admin-dashboard/addons-list/components/Search.js
- assets/react/admin-dashboard/addons-list/context/AddonsContext.js
1. When search any addon using name and the click the enable/disable toggle, the searched item disappeared. (Fix)
> Fixed addon list rendering issue when search is enabled.

- assets/scss/front/course-spotlight/quiz.scss
- templates/single/quiz/parts/fill-in-the-blank.php
Fixed the line break issue on fill in the blanks quiz
Task URL
https://ollyo.atlassian.net/browse/TUTOR-1709
> Fixed quiz fill in the blank line break issue

- classes/Utils.php
- includes/tutor-general-functions.php
- includes/tutor-template-functions.php
- models/CourseModel.php
- models/QuizModel.php
`create-bundle` new slug added
Helper functions added:
`tutor_permission_denied_template`
`tutor_set_flash_message `
> Helper Functions & Create Bundle Slug Added

- assets/react/front/tutor-front.js
- assets/scss/front/index.scss
- assets/scss/frontend-dashboard/_snackbar.scss
- assets/scss/frontend-dashboard/index.scss
- includes/tutor-general-functions.php
`tutor_snackbar ` function added to show snack bar on the frontend
based on the given title & action buttons
> Reusable Snackbar for Displaying on the Frontend 🎉 

- classes/Utils.php
- models/QuizModel.php
Deleted Unused  Utils Class Methods
- get_quiz_answer_options_by_question
- get_quiz_answers_by_ids
Moved Utils Class Methods to QuizModel
- get_quiz_attempt
- get_total_quiz
> Code refactor and util helper move to Quiz Model

- classes/Utils.php
- WPCS fix
- Refactor code
- Unused deprecated method `get_course_id_by_assignment` removed
> WPCS and code refactor

- assets/react/course-builder/lesson.js
- classes/Lesson.php
- views/modal/edit-lesson.php
Need to merge this PR also
https://github.com/themeum/tutor-pro/pull/267
> 🎉 Lesson audio/mp4 support added

- assets/react/course-builder/lesson.js
- assets/react/course-builder/quiz.js
- classes/Quiz.php
- templates/single/quiz/parts/question.php
- views/modal/question_form.php
https://github.com/themeum/tutor-pro/pull/269
> 🎉 WP editor support to quiz question description

- classes/Options_V2.php
- classes/Shortcode.php
- classes/Template.php
https://github.com/themeum/tutor-pro/pull/275
> Hook added to extend tutor 

- assets/react/admin-dashboard/tutor-admin.js
- assets/react/front/dashboard/index.js
- views/fragments/announcement-list.php
- views/pages/course-list.php
- views/qna/qna-table.php
> Fix - last row of tutor table's context menu not visible properly.

- classes/Withdraw.php
- models/WithdrawModel.php
- templates/dashboard/withdraw.php
- views/options/template/common/reset-button-template.php
- views/pages/add_new_instructor.php
- views/pages/withdraw_requests.php
With
- Some translation issues fixes.
- WPCS fixes.
> Fix: Instructors can make withdrawal requests greater than their available balance.

- assets/scss/front/course-spotlight/index.scss
- views/quiz/header-context/course-single-previous-attempts.php
- Latex expression not showing inline
- Missing whitespace between label and value on quiz attempt page.
> Various fixes

- assets/react/front/tutor-front.js
- assets/scss/front/course-spotlight/_players.scss
- classes/Lesson.php
- templates/single/lesson/content.php
Prevent students from completing any video lesson to a certain percentages.
> Control video lesson completion functions added to video player

- assets/react/front/tutor-front.js
- assets/scss/front/course-spotlight/_players.scss
- Fix youtube player design issue.
- Fix video does not start where left off sometimes.
- Only disable forward seeking if complete percentage option is enabled.
> Fix tutor player design and seeking issue

- assets/react/front/tutor-front.js
- templates/single/lesson/content.php
- Disable video watch restrictions for preview lessons. 
- Enable forward seeking to max watch time.
> Update require course complete condition

- assets/scss/front/course-spotlight/_sidebar.scss
- models/QuizModel.php
- templates/single/assignment/content.php
- templates/single/lesson/lesson_sidebar.php
Related PR https://github.com/themeum/tutor-pro/pull/318
> 🎉 New: Spotlight mode now features distinct icons for complete, pass, fail, and pending statuses.

- models/CourseModel.php
- templates/single/common/header.php
Included
- **Update:** on auto course complete redirect to course details with review popup.
> Auto course complete restriction on strict mode if student not passed quiz or assignment.

- templates/public-profile.php
Social links aren't working on the Instructor profile page ( mobile view )
card link : https://ollyo.atlassian.net/browse/TUTOR-1978
> profile page social link mobile device issue -TUTOR-1978

- classes/Instructor.php
- classes/Instructors_List.php
- classes/Quiz.php
- views/pages/instructors.php
instructor rejection new action added, and email not  sending instructor rejection issue fixed
> instructor reject action for email issue

- classes/Lesson.php
> hook added for email triggers

- classes/Utils.php
https://github.com/themeum/tutor-pro/pull/388
> Additional param added to utils helper

- assets/scss/admin-dashboard/v2/_general.scss
- classes/Options_V2.php
- classes/Rewrite_Rules.php
- classes/Tutor_Base.php
- Assignment & quiz base permalink update support
- Zoom & Google Meet lesson's permalink consistent with all course content
> Base permalink update support added

- classes/Upgrader.php
https://github.com/themeum/tutor-pro/pull/433
> Upgrader added for version 2.6.0

- classes/Lesson.php
- classes/Permalink.php
- classes/Tutor.php
- classes/Tutor_Setup.php
- classes/Upgrader.php
Now permalink update will be handled programmatically when it required.
**Events**
- When tutor setup finished
- When base permalink updated ( courses, lessons, quizzes, assignments )
- [More in ](https://github.com/themeum/tutor-pro/pull/434)
> 🎉 New: Auto permalink update feature added

- classes/Utils.php
- classes/WooCommerce.php
- HPOS support added
- Order autocomplete
> 🎉 Latest WooCommerce compatibility

- includes/tutor-general-functions.php
Function name `tutor_getallheaders`
> New Utility Function Added to Get All Headers

- includes/tutor-general-functions.php
- models/CourseModel.php
A new `tutor_conditional_buttons` utility function was added`
`CourseModel:: can_complete_course ` method back to the previous state
> Utility Function Added for The Course Entry Box Buttons

- classes/Assets.php
- classes/Course.php
- classes/Utils.php
`wp_enqueue_media` enqueued wp media to get access to the wp media manager
App configuration object added
> 📸 WP Media Support & Application Configuration Object Added

- classes/Course.php
https://github.com/themeum/tutor-pro/pull/472
> Helper methods and constants pulled from PRO

- classes/Q_and_A.php
- templates/dashboard/question-answer.php
- views/qna/qna-single.php
Details: https://ollyo.atlassian.net/browse/TUTOR-2138
1. HTML Injection via Q&A
2. Missing Authorization
> Fix - QnA security

- classes/Quiz.php
- classes/RestAPI.php
- classes/Tutor_Setup.php
- models/QuizModel.php
- restapi/REST_Author.php
- restapi/REST_Course.php
- restapi/REST_Course_Announcement.php
- restapi/REST_Lesson.php
- restapi/REST_Quiz.php
- restapi/REST_Rating.php
- restapi/REST_Response.php
- restapi/REST_Topic.php
- restapi/RestAuth.php
- templates/single/assignment/content.php
- All the read APIs improved
- Extendability improved
- WPCS errors fixed & refactored
> REST API Improvements

- classes/Ajax.php
API issues fix
Dependent PR
https://github.com/themeum/tutor-pro/pull/504
> API: Review api functionality issue fix

- restapi/REST_Rating.php
- Fixed the get api for `course-rating`
Task url
https://ollyo.atlassian.net/browse/TUTOR-2101
> API: Review get api fix

- assets/react/v3/shared/components/modals/Modal.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
- assets/react/v3/shared/config/constants.ts
Issue: https://ollyo.atlassian.net/browse/TUTOR-2171
> [FE] Update the modal header and accept the children

- assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
Issue: [Jira](https://ollyo.atlassian.net/browse/TUTOR-2184)
> [FE] Create question description field

- assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
- assets/react/v3/shared/config/styles.ts
Issue: [Jira](https://ollyo.atlassian.net/browse/TUTOR-2182)
> [FE] Create an answer explaination field

- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/shared/components/fields/FormInputWithPresets.tsx
- assets/react/v3/shared/hooks/usePortalPopover.tsx
Issue: [Jira](https://ollyo.atlassian.net/browse/TUTOR-2185)
> [FE] Create FieldInputWithPreset field type

- assets/react/v3/shared/molecules/Card.tsx
Issue: [Jira](https://ollyo.atlassian.net/browse/TUTOR-2186)
> [FE] Create a collapsible card

- classes/Course_List.php
- views/pages/question_answer.php
- views/qna/qna-single.php
- Security issue fix on question details
- Security issue on course delete user permission
> Security issues fixes

- package.json
- readme.txt
- tutor.php
- Changelog added
- Version number updated
- Gulp issue fix
> Tutor LMS v2.7.1 update

- assets/react/admin-dashboard/segments/image-preview.js
- classes/Tutor.php
- templates/dashboard/assignments/submitted.php
Issue fixed : 
- TUTOR 2082 : commission ratio
- TUTOR 2108 : assignment submission time
-  TUTOR-2228 : fixed first time installation error
> 2.8.0 issue fixes

- assets/react/front/course/_spotlight-quiz-timing.js
- assets/react/front/course/_spotlight-quiz.js
- classes/Course.php
- views/quiz/attempt-details.php
TUTOR-1989 : Fixed answer required
TUTOR-2232 : fixed attempt details warning
TUTOR-2078: hide course product on shop page fix
> 2.7.2 issue fixes

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/course-builder/utils/utils.ts
feat: Added button for `back to legacy` and `redirect` to edit page after course creation
> feat: Added button for back to legacy and redirect after course creation

- assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
- assets/react/v3/shared/utils/util.ts
Added `calculateTotalChildren` to calculate all nested children
> chore: Refactor code to calculate total children recursively

- classes/Course.php
> Course material multiline, course price set and default qn, public course off

- classes/Admin.php
- classes/Tutor.php
- composer.json
- ecommerce/OrderController.php
- models/OrderModel.php
- views/pages/ecommerce/order-list.php
Total 8 new tables has been introduced
> Ecommerce Database Schema Design

- assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
- assets/react/v3/entries/order-details/components/order/Payment.tsx
- assets/react/v3/entries/order-details/services/order.ts
- assets/react/v3/shared/components/fields/FormTextareaInput.tsx
> Add mark as paid modal

- assets/react/v3/entries/order-details/components/layout/Topbar.tsx
- assets/react/v3/entries/order-details/components/modals/CancelOrderModal.tsx
- assets/react/v3/shared/atoms/Alert.tsx
- assets/react/v3/shared/atoms/Avatar.tsx
> Add cancel order modal

- classes/Tutor.php
- models/OrderModel.php
- net_payment added
- order_price removed 
- subtotal_price renamed 
- bundleModel handled for free version
I've requested to merge on `v3` because Sajeeb vai needs the changes
> Order net payment

- assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
- assets/react/v3/shared/atoms/Button.tsx
- assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
- assets/react/v3/shared/components/fields/FormInputWithContent.tsx
- assets/react/v3/shared/components/fields/FormSelectInput.tsx
- assets/react/v3/shared/components/fields/FormSelectUser.tsx
- assets/react/v3/shared/components/fields/FormTagsInput.tsx
- assets/react/v3/shared/molecules/DropdownButton.tsx
- assets/react/v3/shared/utils/style-utils.ts
- assets/react/v3/shared/utils/validation.ts
> Improve input field's focus design along with the error state.

- assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
- assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
> Fix the discount modal's pricing calculation issue

- assets/react/v3/entries/order-details/components/App.tsx
- assets/react/v3/entries/order-details/components/order/Activities.tsx
- assets/react/v3/entries/order-details/components/order/Summary.tsx
- assets/react/v3/shared/atoms/Toast.tsx
- assets/react/v3/shared/utils/style-utils.ts
If not course selected for some reason then it will show a message.
> :bug: fix an issue of the order summary design

- .github/workflows/wpcs.yml
- classes/Course.php
Deprecated: Function `print_emoji_styles` is deprecated since version 6.4.0!
> Fix - deprecation warning in course builder

- assets/react/v3/entries/tax-settings/index.tsx
- classes/Assets.php
- classes/Options_V2.php
- classes/Tutor.php
- ecommerce/Ecommerce.php
- ecommerce/HooksHandler.php
- ecommerce/OptionKeys.php
- ecommerce/OrderController.php
- views/options/option_blocks.php
- views/options/settings.php
- views/options/template/basic.php
- views/pages/ecommerce/coupon-list.php
- views/pages/ecommerce/order-list.php
- webpack.config.js
`HooksHandler` new classed for handling order custom hooks
Storing order meta data as activities on bulk actions
`refund_amount` new column added on the orders table
> Store Order Activities on Bulk Actions

- ecommerce/OrderController.php
- models/OrderActivitiesModel.php
- models/OrderModel.php
Task url
https://app.clickup.com/t/86eprdg6v
> Order cancel reason meta added

- assets/react/admin-dashboard/segments/options.js
- classes/Options_V2.php
- classes/Utils.php
- ecommerce/HooksHandler.php
- ecommerce/OptionKeys.php
- ecommerce/Settings.php
- includes/tutor-general-functions.php
- templates/loop/add-to-cart-tutor.php
- templates/loop/course-price-tutor.php
- templates/loop/course-price-woocommerce.php
- templates/single/course/add-to-cart-tutor.php
- views/modal/ecommerce/add-manual-payment.php
- views/modal/ecommerce/manual-payment.php
- views/options/option_blocks.php
- views/options/settings.php
- views/options/template/basic.php
1. Ecommerce settings
a. Basic
b. Payment
c. Checkout
2. Custom manual payment create, update & delete
3. Add to cart button on the course list & details page
> Ecommerce Settings, Custom Manual Payment & Add to Cart Functionalities

- assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
- assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
- assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/shared/components/fields/FormCoursePrerequisites.tsx
- assets/react/v3/shared/components/fields/FormSelectUser.tsx
- assets/react/v3/shared/components/fields/FormVideoInput.tsx
- assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
- refactored the `FormVideoInput` component and added checks on some edge cases.
- Fixed `SchedleOtions` value not updating.
- Fixed the `Instructors` field not showing
- Fixed all `instructors` not showing
- Updated the `FormFillinTheBlanks` component to display an error message if the dash count is not equal to the answer count.
- Fixed issues when `post status` is not saving 
- Fix duplicate option index in `Matching` and `MultipleChoiceAnswer`
- Used `userQuery` for author lists
- Added `helptext` in lesson model `title` and `description`
> 🛠️ fix: fixed some issues and refactored some codes.

- helpers/QueryHelper.php
- Made access public for outer access
- `-1` for getting all record without limit support added
> Query helper updated

- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/subscription/PreviewItem.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/shared/components/fields/FormSelectUser.tsx
Fixed Issues:
- [Duration and Deadline are not showing on assignment](https://app.clickup.com/t/86eq271jk)
- [Author and Instructor list is not updating correctly](https://app.clickup.com/t/86eq27ffr)
> Updated instructor options in CourseBasic component

- assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetCard.tsx
- assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
- assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingCard.tsx
- assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
- assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/shared/molecules/ConfirmationPopover.tsx
Fixed Issues:
- [Implement delete popover and add default Duration in zoom meeting. ](https://app.clickup.com/t/86eq2uckv)
> refactor: Add delete confirmation popover and Update ZoomMeetingForm

- classes/Tutor.php
- ecommerce/AdminMenu.php
- ecommerce/Settings.php
- parent id added to track subscription's order
- hook added to add subscriptions menu
- currency default value updated
> Hook and table field added

- assets/react/v3/entries/coupon-details/components/coupon/CouponInfo.tsx
- assets/react/v3/entries/coupon-details/components/coupon/CouponPreview.tsx
- assets/react/v3/entries/coupon-details/components/layout/Main.tsx
- assets/react/v3/entries/coupon-details/components/layout/Topbar.tsx
- assets/react/v3/entries/coupon-details/services/coupon.ts
- assets/react/v3/entries/pro/manual-enrollment/components/CourseCard.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/FormSelectCourse.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/FormSelectStudents.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/SelectedStudents.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/layout/Main.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/layout/Topbar.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/modals/CourseListModal/CourseListTable.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/modals/CourseListModal/SearchField.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/modals/StudentListModal/SearchField.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/modals/StudentListModal/StudentListTable.tsx
- assets/react/v3/entries/pro/manual-enrollment/components/modals/StudentListModal/index.tsx
- assets/react/v3/shared/components/fields/FormSelectInput.tsx
- classes/Assets.php
- ecommerce/CouponController.php
- models/CouponModel.php
- views/pages/ecommerce/coupon-list.php
- webpack.config.js
- Coupon preview error fixed
- Tutor currency symbol updated in global object
- coupon_code required removed
- Redirect to list page after coupon create
- Coupon issues fixed
- CourseCard design fixed
- Background color removed from FormSelectInput
- Coupon discount and type updated in coupon list
- @wordpress/i18n used instead of wp.i18n
- @wordpress/i18n support added to webpack
- Display delete permanently on trash tab
- coupon_status field added in edit mode
> Various issues fixed 

- classes/Course.php
https://app.clickup.com/t/86eq2713x
> Fix: error occur when insert media video, audio on WP editor

- ecommerce/OrderController.php
- models/OrderModel.php
- templates/dashboard/purchase_history.php
1. **get_user_orders** method added on the Order Model
2. **purchase-history** template updated to show Tutor Orders
> Order History Functionalities Added to Show on The Student Dashboard

- assets/react/v3/entries/course-builder/components/App.tsx
- assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
- assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
- assets/react/v3/entries/course-builder/components/layouts/Layout.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/entries/course-builder/components/modals/SubscriptionModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/services/curriculum.ts
- assets/react/v3/entries/course-builder/services/quiz.ts
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/entries/order-details/components/App.tsx
- assets/react/v3/shared/atoms/Button.tsx
- assets/react/v3/shared/atoms/WPEditor.tsx
- assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
- assets/react/v3/shared/components/fields/FormSelectInput.tsx
- assets/react/v3/shared/components/fields/FormTopicPrerequisites.tsx
- assets/react/v3/shared/components/fields/FormWPEditor.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
- assets/react/v3/shared/molecules/DropdownButton.tsx
Fixed Issues:
- [Deleting attachments disables updates to lessons, assignments, or courses.](https://app.clickup.com/t/86eq4ru44)
- [All data removed from basic and additional tab after creating zoom meeting](https://app.clickup.com/t/86eq4t39y)
- [Content drip: "Finishing Prerequisite" displays the site's courses, not the course content.](https://app.clickup.com/t/86eq4vbnq)
- [Content Drip is not working](https://app.clickup.com/t/86eq4w5te)
> Feat: Added FormTopicPrerequisites and Fixed some issues.

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
- assets/react/v3/entries/coupon-details/components/coupon/CouponValidity.tsx
- assets/react/v3/entries/coupon-details/components/modals/CourseListModal/CourseListTable.tsx
- assets/react/v3/entries/coupon-details/services/coupon.ts
- assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
- assets/react/v3/entries/order-details/components/modals/RefundModal.tsx
- assets/react/v3/entries/order-details/components/order/OrderItem.tsx
- assets/react/v3/entries/order-details/components/order/Payment.tsx
- assets/react/v3/entries/order-details/components/order/Student.tsx
- assets/react/v3/entries/order-details/components/order/Summary.tsx
- assets/react/v3/entries/order-details/services/order.ts
- assets/react/v3/entries/pro/manual-enrollment/components/modals/CourseListModal/CourseListTable.tsx
- assets/react/v3/shared/utils/currency.ts
- classes/Assets.php
- classes/Course.php
- models/CourseModel.php
- templates/ecommerce/checkout-details.php
1. disabledBefore validation added to coupon end date
2. `courses` changed to `items` in order
3. Price format updated with selected currency
4. Checkout error message design updated
5. Subscription course support added to coupon create
> Random issue fixes

- assets/scss/front/course-spotlight/quiz.scss
- templates/single/quiz/parts/choice-box.php
- templates/single/quiz/parts/matching.php
- views/quiz/attempt-details.php
- Question type `single_choice` and `multiple_choice` now handled with `multiple_choice` type.
- Question type `image_matching` and `matching` now handled with `matching` type.
> Question type merged support added to quiz attempt

- classes/Utils.php
- ecommerce/EmailController.php
- ecommerce/HooksHandler.php
- ecommerce/OrderController.php
- ecommerce/PaymentGateways/Paypal/src/Payments/Paypal/Paypal.php
- ecommerce/Settings.php
- helpers/QueryHelper.php
- models/CouponModel.php
- models/OrderModel.php
- views/options/settings.php
1. Functionalities added to reflect order earnings on the Report & Analytics pages
2. Payment with Paypal support added
> Report, Analytics, Refund & Papal Payment Gateway

- classes/Course.php
- ecommerce/CheckoutController.php
- ecommerce/Ecommerce.php
- ecommerce/PaymentHandler.php
- templates/dashboard/create-course.php
- Fix - co-author can not access course edit
- Gateway class fetch refactor
> Fix and refactor

- ecommerce/CheckoutController.php
- ecommerce/PaymentGateways/Configs/PaymentUrlsTrait.php
- ecommerce/PaymentGateways/Configs/PaypalConfig.php
- ecommerce/PaymentGateways/Configs/StripeConfig.php
- ecommerce/PaymentGateways/GatewayBase.php
- ecommerce/PaymentGateways/Paypal/src/Config/Repository.php
- ecommerce/PaymentGateways/Paypal/src/Contracts/Core/ContainerContract.php
- ecommerce/PaymentGateways/Paypal/src/Core/Container.php
- ecommerce/PaymentGateways/Paypal/src/Core/Payment/BasePayment.php
- ecommerce/PaymentGateways/Paypal/src/Core/Support/Arr.php
- ecommerce/PaymentGateways/Stripe/src/Config/Repository.php
- ecommerce/PaymentGateways/Stripe/src/Contracts/Core/ContainerContract.php
- ecommerce/PaymentGateways/Stripe/src/Core/Container.php
- ecommerce/PaymentGateways/Stripe/src/Core/Payment/BasePayment.php
- ecommerce/PaymentGateways/Stripe/src/Core/Support/Arr.php
- ecommerce/PaymentGateways/Stripe/src/Core/Support/System.php
- ecommerce/PaymentGateways/Stripe/src/Payments/Stripe/Stripe.php
- ecommerce/PaymentGateways/Stripe/src/Payments/Stripe/composer.json
- models/CouponModel.php
- templates/ecommerce/checkout-details.php
1. Recurring payments for Stripe Payment Gateway added
**How to make recurring payment**
```
$obj = \Tutor\Ecommerce\Ecommerce::get_payment_gateway_object(Tutor\PaymentGateways\StripeGateway::class);
$obj->make_recurring_payment(147, 10); // order_id, amount
```
> Recurring Payments

- ecommerce/CheckoutController.php
- ecommerce/CouponController.php
- ecommerce/OrderController.php
- helpers/DateTimeHelper.php
- models/CouponModel.php
- models/OrderModel.php
- templates/ecommerce/checkout-details.php
- Update: Checkout coupon apply method update
- Fix: Item name not fetch if plan purchase
- Fix: Plan price fetched zero
- Fix: Inaccurate date time
> Various issue fixes

- classes/Course.php
- classes/Options_V2.php
https://app.clickup.com/t/86eq8ued6
> Course builder - localized only required settings and added key to detect ChatGPT api key provided or not.

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
- assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
- assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/components/layouts/Layout.tsx
- assets/react/v3/entries/course-builder/components/layouts/Tracker.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/entries/course-builder/components/modals/SetupOpenAiModal.tsx
- assets/react/v3/entries/course-builder/components/subscription/OfferSalePrice.tsx
- assets/react/v3/entries/course-builder/components/subscription/SubscriptionItem.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/shared/atoms/WPEditor.tsx
- assets/react/v3/shared/components/fields/FormCoursePrerequisites.tsx
- assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
- assets/react/v3/shared/components/fields/FormFileUploader.tsx
- assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
- assets/react/v3/shared/components/fields/FormVideoInput.tsx
- assets/react/v3/shared/components/fields/FormWPEditor.tsx
- assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
- assets/react/v3/shared/utils/style-utils.ts
Features:
- WP Editor Support for Lesson Descripiton
- WP Editor AutoResizefuntionality
- WP Editor read-only functionality
- Made `tutor settings` optional
Fixed Issues:
- Legacy Mode for Lesson Description
- The 'Publish Course' button fails to operate when switching the Payment Category.
-*Refactored Some Codes*
> 🛠️ Fix: Multiple issue fix

- assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/utils/utils.ts
- Added useEffect hook to CourseSettings component to handle price category changes
- Disabled enrollment expiry input field when price category is 'subscription'
- Removed unnecessary code in Header component
> refactor: Refactor CourseSettings and Header components

- classes/Admin.php
- classes/Utils.php
> Add admin warning message when Tutor LMS unstable version installed

- classes/Lesson.php
https://app.clickup.com/t/86eq8uec2
> Made lesson description optional and removed unused lesson meta-boxes

- assets/react/admin-dashboard/segments/filter.js
- classes/Admin.php
- classes/Course.php
- ecommerce/OrderController.php
- helpers/DateTimeHelper.php
- models/OrderModel.php
- templates/dashboard.php
- Wrong order status count
- Warning message showing on subscription list bulk action
- Admin bar new course item removed
- Course category and tags can not be cleared
- Old course build appeared for free user
- Used new date helper `wp_date` instead of `date_i18n` for accurate date
> Multiple issue fixes

- classes/Assets.php
- classes/Course.php
- gulpfile.js
- webpack.config.js
Also removed previous course builder css, js enqueues.
> Course builder translation fixed. 

- classes/Earnings.php
- helpers/DateTimeHelper.php
- includes/translate-text.php
- Refactor method
- Add danger badge for cancelled status
> Fix - earning data not storing for subscription order

- assets/react/front/_select_dd_search.js
- ecommerce/Settings.php
- views/options/field-types/select.php
1. Dropdown item active state added to tutor select
2. Select option error fixed in select field type
3. select_options false added to some settings
> Dropdown item active state added to tutor select

- models/OrderMetaModel.php
- models/OrderModel.php
- templates/ecommerce/checkout-details.php
- templates/ecommerce/checkout.php
- Filter hook added on checkout to prevent duplicate plan subscription.
> Delete course progress on enrollment delete and OrderMetaModel updated

- assets/react/v3/entries/course-builder/components/additional/CertificateEmptyState.tsx
- assets/react/v3/entries/course-builder/components/additional/CoursePrerequisitesEmptyState.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGeneration.tsx
- assets/react/v3/entries/course-builder/components/modals/ProIdentifierModal.tsx
- assets/react/v3/entries/course-builder/pages/Additional.tsx
- assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
- assets/react/v3/shared/molecules/EmptyState.tsx
The overlay button in the ContentGeneration component is now disabled when the pointer value matches the current index. This change ensures that the button cannot be clicked when the component is in a loading state or when the pointer value is already set to the current index.
Refactor the ContentGeneration component in the ai-course-modal directory.
> Fix: Ai Course Genration Navigation

- assets/react/admin-dashboard/segments/options.js
- assets/scss/admin-dashboard/v2/components/_nav-tab.scss
- classes/Options_V2.php
- ecommerce/Settings.php
- views/options/settings.php
- Native e-commerce menu moved under monetization settings tab
- Submenu search support added
- Code refactor
> Settings sub-menu support added added 🎉

- ecommerce/OrderController.php
- models/OrderModel.php
- Re-use in subscription manual active
> Re-useable method for mark as paid order

- assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
Fixed Question form not updating after whole quiz form reset.
> refactor: Refactor QuestionForm component to include usePrevious hook

- assets/react/admin-dashboard/addons-list/components/AddonCard.js
- assets/react/v3/shared/utils/util.ts
- assets/scss/admin-dashboard/v2/components/_tooltip.scss
- classes/Options_V2.php
- views/elements/bulk-confirm-popup.php
- views/elements/common-confirm-popup.php
This commit refactors the AddonCard component in the addons-list directory. It fixes some formatting issues and improves the readability of the code. The changes include:
- Reformatting the className attribute in the JSX code to improve readability
- Fixing the indentation and line breaks in the JSX code
- Updating the tooltip text for required plugins and push notification requirements
The changes in this commit enhance the code structure and make it easier to maintain and understand.
> Content v3

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
- assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
- assets/react/v3/entries/course-builder/components/layouts/CanvasHead.tsx
- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/pages/Curriculum.tsx
- assets/react/v3/entries/course-builder/services/curriculum.ts
- assets/react/v3/shared/components/fields/FormVideoInput.tsx
- classes/Course.php
- classes/Lesson.php
Also refactored and improved stability
> feat: Exit Button Added to Course Builder Header

- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGeneration.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
- assets/react/v3/entries/course-builder/components/modals/CertificatePreviewModal.tsx
- assets/react/v3/entries/course-builder/components/modals/ExitCourseBuilderModal.tsx
- assets/react/v3/entries/course-builder/components/modals/H5PContentListModal.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
- Refactored the ContentGeneration component in the AI course modal to improve readability and maintainability.
- Updated the icons in the TopicContent component in the curriculum to use a new color.
> Random Fixes

- assets/react/v3/entries/course-builder/components/ai-course-modal/BasicPrompt.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentAccordion.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGeneration.tsx
- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGenerationContext.tsx
- assets/react/v3/entries/course-builder/hooks/useGenerateCourseContent.ts
- assets/react/v3/entries/course-builder/services/magic-ai.ts
- assets/react/v3/shared/components/magic-ai-image/ImageGeneration.tsx
- assets/react/v3/shared/components/modals/AITextModal.tsx
- assets/react/v3/shared/utils/api.ts
- package-lock.json
- package.json
Refactor several components in AI course modal to enhance user experience, error handling, and code organization. This pull request includes the following changes:
- Refactored error handling and improved user experience in AI course modal components.
- Refactored image handling in AI course modal components.
- Set focus to the prompt input in the Image generation modal.
- Set focus to the prompt input on load in AITextModal.
- Imported necessary dependencies and removed unused code in AI course modal components.
- Added an abort signal for course content generation requests, allowing for content generation cancellation using an AbortController.  
These changes aim to streamline the functionality and usability of the AI course modal.
> ✨feat: Implemented mutation cancelation for AI content generation

- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/pages/Additional.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
- assets/react/v3/shared/components/fields/FormFileUploader.tsx
- assets/react/v3/shared/components/magic-ai-image/styles.ts
This pull request includes refactoring to improve code readability in the LessonModal and CourseBasic components.
> ⚙️ Refactor: Fix Button Styles in LessonModal and CourseBasic components.

- assets/react/v3/entries/course-builder/components/ai-course-modal/ContentGeneration.tsx
**Changes Made:**
- Updated the layout and buttons of the ContentGeneration component.
This pull request aims to improve the user experience by making the layout more visually appealing and enhancing the functionality of the buttons within the ContentGeneration component.
> ✨ Update ContentGeneration component layout and buttons.

- assets/react/v3/shared/utils/util.ts
Here is a description for the pull request:
This pull request refactors the left bar height calculation in the utility functions. The changes ensure that the left bar height is adjusted correctly to provide a better user interface experience.
The commit message provides a summary of the changes made:
- 🔨 refactor(utils): adjust left bar height calculation
> 🔨 refactor(utils): adjust left bar height calculation

- assets/react/v3/entries/payment-settings/fields/OptionWebhookUrl.tsx
- assets/react/v3/shared/utils/util.ts
**Pull Request Description:**
**What does this PR do?**
This PR improves the clipboard copy functionality in the `OptionWebhookUrl` component. It enhances the user experience by providing a better way to copy the webhook URL.
**Why is this change important?**
Allowing users to easily copy the webhook URL is an important feature for the application. This change improves the existing clipboard copy functionality, making it more user-friendly and reliable.
**How does this change work?**
The commit in this PR includes the following changes:
<###>✨ feat: Improve clipboard copy functionality in OptionWebhookUrl component</###>
These changes focus on enhancing the clipboard copy feature in the `OptionWebhookUrl` component, making it more intuitive and reliable for users.
> ✨ feat: Improve clipboard copy functionality in OptionWebhookUrl component

- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
This pull request removes the character limit for course, lesson, and assignment titles in the application.
> ✨ refactor: remove character limit for course, lesson, and assignment titles

- assets/react/v3/entries/course-builder/components/layouts/Header.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/shared/atoms/ImageInput.tsx
- assets/react/v3/shared/atoms/MagicButton.tsx
- assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
- assets/react/v3/shared/components/fields/FormImageInput.tsx
This pull request refactors the Course Builder header to a redesigned version for improved aesthetics and functionality. 
Changes Made:
- Redesigned the course builder header
<###>
> 🎨refactor: Course Builder Hader redesign

- assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
- assets/react/v3/entries/course-builder/components/course-basic/ContentDripSettings.tsx
- assets/react/v3/shared/components/fields/FormRadioGroup.tsx
- assets/react/v3/shared/components/fields/FormTextareaInput.tsx
- assets/react/v3/shared/components/fields/FormVideoInput.tsx
**Description:**
This pull request enhances the video source detection logic in the `FormVideoInput` component. The main changes include:
- Improved the detection of video sources to provide a better user experience.
- Optimized the logic to handle various video source scenarios more effectively.
- Introduced new features to support additional video input options.
These changes aim to improve the overall functionality and reliability of the video input feature within the form.
> ✨🔖 feat(FormVideoInput): Enhance video source detection logic

- ecommerce/AdminMenu.php
- ecommerce/HooksHandler.php
- models/OrderModel.php
https://app.clickup.com/t/86eqe4qzv
> Badge count implemented for backend order menu

- classes/Utils.php
- ecommerce/AdminMenu.php
- views/pages/course-list.php
With
- Course list price column size updated to adjust price data
- Order type clause added to count order menu badge
Helper re-used in
https://github.com/themeum/tutor-pro/pull/728
> Re-useable Helper added to get prices with tax info

- classes/Course.php
- classes/Utils.php
> Attached woo product not get selected issue fixed

- classes/Utils.php
- models/OrderModel.php
- templates/dashboard/purchase_history.php
https://app.clickup.com/t/86eqja4f3
> Order history date range filter issue fixed

- assets/react/front/pages/cart.js
- ecommerce/CartController.php
dispatch custom event after added to cart
> dispatch custom event after added to cart

- classes/Course.php
- classes/Utils.php
> Formatted supported video source list added to tutor object

- classes/Utils.php
https://app.clickup.com/t/86eqgng41
> Fix - assignment is loading even tutor pro is not active or assignment addons

- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/shared/components/fields/FormWPEditor.tsx
Here is the pull request description:
This pull request addresses a fix for the WpEditor and CustomEditors in the WordPress Admin area. The changes include:
1. Added conditional rendering for the WP Editor button in the LessonModal component, ensuring the button is displayed only when the user has the necessary permissions.
2. Implemented a filter to display editors based on the user's roles, improving the accessibility and functionality of the FormWPEditor component.
These changes aim to enhance the overall user experience and ensure proper access control for the WordPress Editor features within the application.
> 🛠️fix: WpEditor and CutomEdiors wpAdmin access check

- models/OrderModel.php
https://app.clickup.com/t/86eqnf7bv
> Warning issue fixed

- assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
- assets/react/v3/shared/components/fields/FormTextareaInput.tsx
- templates/single/video/video.php
- Video Source Playoad Issue Fixed
- Added conditional `input` based on `tutor pro` for `Question Description`
> Video Source Playoad Issue Fixed

- assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicHeader.tsx
- assets/react/v3/entries/course-builder/components/layouts/Layout.tsx
- assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/shared/components/fields/FormEditableAlias.tsx
- Fixed post alias reseting issue
- Fixed Topic Title not focusing issue
> refcator: Fixed post alias reseting issue

- classes/Quiz.php
- classes/Quiz_Attempts_List.php
- models/QuizModel.php
- views/quiz/attempt-details.php
https://app.clickup.com/t/86eqnuaqq
> Fix: User is unable to delete blank submitted quiz [timeout quiz attempt]

- assets/react/v3/entries/course-builder/services/quiz.ts
> Fix: Number of question not showing after h5p quiz attempt

- models/OrderModel.php
- templates/dashboard/purchase_history.php
Now the **pay** button will appear if the order is complete, the payment method is manual & the user is not enrolled any course of that order.
> Pay now button showing condition updated

- ecommerce/HooksHandler.php
- models/CouponModel.php
- Enrollment email not triggered on re-purchase
- Coupon requirement pass if there is not regular price item
> Issue fixes

- assets/react/front/dashboard/settings/profile.js
- classes/Student.php
- templates/dashboard/settings/social-profile.php
With fix
- social profile data get deleted on profile update
> Update social profile with Ajax instead of form submit

- assets/react/front/course/_spotlight-quiz-timing.js
https://app.clickup.com/t/86eqre0eh
> Reload the page when no attempt remaining 

- assets/react/front/tutor-front.js
> Revert "Fix: vimeo video not playing sound if control video complete percentage settings is enabled"

- assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
- assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
- assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/entries/course-builder/components/modals/SetupOpenAiModal.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/course-builder/services/curriculum.ts
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/shared/atoms/ImageInput.tsx
- assets/react/v3/shared/components/fields/FormFileUploader.tsx
- assets/react/v3/shared/components/fields/FormImageInput.tsx
- assets/react/v3/shared/components/fields/FormVideoInput.tsx
- assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
- assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
- assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
- assets/react/v3/shared/hooks/useWpMedia.ts
- eslint.config.mjs
- package-lock.json
- package.json
- `useWpMedia` hook
- Added `eslint` hook config
> ✨feat: useWpMedia hook introduced

- assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetCard.tsx
- assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingCard.tsx
- assets/react/v3/shared/components/fields/FormFileUploader.tsx
A11y added to
- Course Attachment
- Zoom and Google Meeting
> ⚙️ refactor: A11y added to Additional page

- classes/Student.php
- templates/dashboard/settings/profile.php
https://app.clickup.com/t/86eqxu9ft
> Timezone update for non-admin user only from frontend profile.

- tutor.php
With
- Code refactor and comment update
- Removed unused `instructor_role_name` key from tutor object which encounter error of early translation.
> Removed duplicate helper `str_contains` which already included in WP core

- helpers/QueryHelper.php
- templates/ecommerce/checkout-details.php
https://github.com/themeum/tutor-pro/pull/834
> IN clause support added to update method and sanitize mapping added to insert method

- classes/Utils.php
- ecommerce/HooksHandler.php
- Trigger hook param added to `update_enrollments` utils helper
> Fix - doing enrolment on membership plan purchased

- assets/react/front/course/_archive.js
- ecommerce/HooksHandler.php
- templates/loop/course-price.php
- Subscription enrollment track from course card
- Fix: undefined property
> Filter hook added to extend tutor functionality

- ecommerce/HooksHandler.php
- models/OrderModel.php
https://github.com/themeum/tutor-pro/pull/890
> Update: enrol to bundle courses

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/course-basic/CourseBasicSidebar.tsx
Introduce a setting for membership-only mode and conditionally render the CoursePricing component based on this setting.
> Add membership-only mode setting for CoursePricing component

- classes/Students_List.php
- classes/Utils.php
[Prevent the deletion from the wp user, remove the student mark, and clean the data](https://app.clickup.com/t/86err2pa0)
> Ticket ID: 86err2pa0

- classes/Utils.php
- templates/single/course/course-entry-box.php
- templates/single/course/course-topics.php
1. Fix: Static loader removed for logged out users
2. Fix: stripslashes added to answer_explanation
3. Meeting countdown not displaying in topic list fixed
> Zoom, Loader, and slash issues fixed 

- assets/react/v3/shared/atoms/SVGIcon.tsx
Improve performance and user experience by adding memoization to the SVGIcon component and implementing a loading state while icons are being fetched.
> ✨ Enhance SVGIcon component with memoization and loading state

- assets/react/v3/shared/atoms/WPEditor.tsx
- assets/react/v3/shared/components/FocusTrap.tsx
- assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
- assets/react/v3/shared/components/modals/ModalWrapper.tsx
Remove unused focus management logic and replace it with the FocusTrap component in modal wrappers for improved accessibility and focus handling.
> 🔧 Refactor modal focus management with FocusTrap component integration

- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
- assets/react/v3/entries/course-builder/components/fields/FormQuestionDescription.tsx
- assets/react/v3/entries/course-builder/components/fields/FormQuestionTitle.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/shared/atoms/WPEditor.tsx
- assets/react/v3/shared/components/fields/FormWPEditor.tsx
Integrate the FormQuestionTitle component into QuizModal, improving the editing functionality and accessibility of the FormQuestionTitle component. Enhance the FormQuestionDescription and WPEditor components with better editing capabilities and focus management.
> ✨ Integrate FormQuestion components and enhance editing features in QuizModal

- assets/react/v3/shared/components/fields/FormSelectInput.tsx
Enhance the initial value retrieval and option selection logic in the FormSelectInput component for improved performance and usability.
> ✨Reactor FormSelectInput Disable logic and initial value retrieval

- assets/react/v3/shared/components/fields/FormDateInput.tsx
- package-lock.json
- package.json
Enhance ISO date handling in the FormDateInput component and update the react-day-picker library to version 9.6.7 for better functionality.
> ✨ fix: improve date parsing and update react-day-picker dependency

- assets/react/v3/shared/utils/util.ts
Improve the `formatSubscriptionRepeatUnit` function to support singular units and enhance overall readability. This change simplifies the logic and adds a new option to display singular forms when applicable.
> ✨ Enhance formatSubscriptionRepeatUnit for readability and singular support

- assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
Correct the value for membership plans in the appliesToOptions to ensure accurate representation in the application.
> 🛠️ Fix membership plans value in appliesToOptions

- assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
- assets/react/v3/entries/coupon-details/components/layout/Main.tsx
- assets/react/v3/entries/coupon-details/services/coupon.ts
Improve coupon handling to support specific membership plans, allowing for more flexible discount applications.
> ✨ Enhance coupon functionality for membership plans

- classes/Course.php
Streamline the setup process for course categories and tags by introducing a validation method for term IDs, ensuring only valid terms are set on the post.
> ✨ Refactor category and tag setup with term ID validation

- assets/react/v3/shared/components/fields/FormVideoInput.tsx
- cypress/e2e/course-builder/02-course-settings.cy.ts
Add data attributes for improved video URL handling in the FormVideoInput component and streamline the course media configuration process.
> 🎥 [TEST] Enhance video URL handling in course media configuration

- classes/Shortcode.php
- Added `category_limit='8'` field on shortcode which allows to limit the category filter shown, if no limit is added all category will show
- Added `show_empty_category='1'` field on shortcode which allows to show or hide the category not assigned to any courses
> Update: Instructor list shortcode category filter

- assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
Streamline character limit validation for quiz settings and add helpful text for input fields to improve user experience.
> 🛠️ Simplify character limit validation and enhance input help text

- assets/react/v3/shared/config/constants.ts
Correct the typo in the visibility control key for course materials to ensure proper functionality.
> ✏️ Fix typo in visibility control key for course materials

- assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
Improved visibility controls for featured images, videos, and exercise files in the LessonModal, improving user experience and customization options.
Current: 
Improved:
> ✨ Enhance LessonModal Layout with visibility controls

- assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
- assets/react/v3/shared/utils/util.ts
Refine the tree generation logic to handle cases where the parent may not be present. Remove unnecessary debug logging from the FormMultiLevelInput component and clarify variable names in the generateTree function.
> ✨ feat: enhance category list tree generation logic

- assets/react/v3/shared/components/fields/FormMultiLevelSelect.tsx
- assets/react/v3/shared/utils/util.ts
Improve the category filtering and processing logic in the generateTree function to handle duplicates and optimize tree generation.
> ✨ Enhance category filtering in generateTree function

- assets/react/v3/entries/course-builder/components/course-basic/EnrollmentSettings.tsx
Update validation rules for enrollment start date and time, and clear related errors when the enrollment period is disabled.
> 🛠️ Fix enrollment date and time validation rules

- assets/react/v3/entries/course-builder/services/course.ts
Refine the logic for setting the pricing product ID based on course price type and monetization settings.
> 🛠️ fix: update pricing product ID logic in convertCourseDataToPayload function

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/tax-settings/components/TaxRates.tsx
- assets/react/v3/entries/tax-settings/components/TaxSettingGlobal.tsx
- assets/react/v3/entries/tax-settings/molecules/Card.tsx
- assets/react/v3/entries/tax-settings/services/tax.ts
- assets/react/v3/shared/atoms/Radio.tsx
- assets/react/v3/shared/components/fields/FormRadioGroup.tsx
- assets/react/v3/shared/utils/style-utils.ts
Introduce tax collection options for single purchases and subscriptions, improve the tax settings UI with better descriptions, and add individual tax control options in the CoursePricing component. Clean up duplicate imports in the CoursePricing component.
> ✨ Add tax collection options and enhance tax settings UI

- assets/react/v3/@types/index.d.ts
- assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
- assets/react/v3/entries/course-builder/services/course.ts
- assets/react/v3/entries/tax-settings/components/TaxRates.tsx
- assets/react/v3/entries/tax-settings/components/TaxSettingGlobal.tsx
- assets/react/v3/entries/tax-settings/molecules/Card.tsx
- assets/react/v3/entries/tax-settings/services/tax.ts
- assets/react/v3/shared/atoms/Radio.tsx
- assets/react/v3/shared/components/fields/FormRadioGroup.tsx
- assets/react/v3/shared/utils/style-utils.ts
> Revert "✨ Add tax collection options and enhance tax settings UI"

- assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
- assets/react/v3/entries/course-builder/services/course.ts
Clarify the naming of tax collection fields in the course pricing interface to enhance understanding and maintain consistency across the codebase.
> 🛠️ Rename tax collection fields for clarity

- assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
- assets/react/v3/entries/course-builder/services/course.ts
Introduce a tax alert for disabled tax collection options in CoursePricing. Restructure tax settings into a nested object for improved organization and simplify the tax settings in CoursePayload. Add tax control logic and update the CourseSellingOption type export accordingly.
> 🧾 Enhance tax collection controls and alerts

- assets/react/v3/entries/import-export/components/App.tsx
- assets/react/v3/entries/import-export/components/Export.tsx
- assets/react/v3/entries/import-export/components/modals/CourseListModal/CourseListTable.tsx
- assets/react/v3/entries/import-export/components/modals/CourseListModal/SearchField.tsx
- assets/react/v3/entries/import-export/components/modals/CourseListModal/index.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/shared/components/modals/CourseCategorySelectModal/CourseListTable.tsx
Introduce lazy loading for the Main component with a suspense fallback. Improve the layout of the ExportModal by adjusting its height and adding gaps to export styles. Add CourseListModal and SearchField components to facilitate course selection during the export process. Update thumbnail width in CourseListTable for better display.
> ✨ feat: Implement lazy loading and enhance export modal layout

- assets/react/v3/entries/import-export/components/modals/CourseListModal/index.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Introduce an `onSelect` prop to the `CourseListModal` to manage course selections. Update the `ExportModal` to utilize this new functionality, enhancing the user experience when selecting courses.
> ✨ feat: add onSelect prop to CourseListModal and update ExportModal for course selection handling

- assets/react/v3/entries/import-export/components/History.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Enhance the Table component in History with rounded corners and borders. Refactor the ExportModal and import-export service for better content handling and structure.
> ✨ Update Table component and refactor ExportModal

- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
Improve the ExportModal to show or hide sub-content labels based on whether items are selected in the parent content, streamlining the user interface for better clarity.
> ✨ Enhance ExportModal to conditionally display sub-content labels

- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Improve user interaction by refining the button enabling logic in the ExportModal and consolidate media file handling in the ExportFormData structure. Update the payload to streamline data processing.
> ✨ Enhance Export Modal and Refactor Data Handling

- assets/react/front/pages/checkout.js
- ecommerce/CheckoutController.php
- templates/ecommerce/checkout-details.php
- templates/ecommerce/checkout.php
- Fix: Payment methods are not showing when coupon removed
- Fix: Non-zero total order get enrolled
- Refactor code
> Refactor code and issue fixes

- assets/react/v3/entries/import-export/components/Export.tsx
- assets/react/v3/entries/import-export/components/modals/CourseListModal/CourseListTable.tsx
- assets/react/v3/entries/import-export/components/modals/CourseListModal/index.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/shared/services/course.ts
- assets/react/v3/shared/utils/endpoints.ts
- views/options/tools.php
Improve the structure and styling of the tools layout, ensure consistent styling for the admin header, and enhance the Export and ExportModal components with better failure reporting and message formatting. Add an option to retain media files during export and update the CourseListTable and CourseListModal to support course bundles and improve data handling.
> ✨ Refactor tools layout and enhance export features

- assets/react/v3/entries/import-export/components/Import.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/components/modals/ImportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
- assets/react/v3/shared/utils/endpoints.ts
Introduce JSON file handling and API integration for import functionality. Enhance import/export features with improved progress handling and error messaging. Optimize error handling in the ImportModal component.
> ✨ Implement import functionality with enhanced error handling and progress tracking

- assets/react/v3/entries/import-export/components/History.tsx
Enhance the delete action in the History component by adding a loading state and improving the button styling for better user experience.
> ✨ Refactor delete action in History component with loading state and improved styling

- assets/react/v3/entries/import-export/components/History.tsx
Update singular labels in the content type configuration to enhance clarity and improve user understanding.
> ✨ Refactor content type configuration for clarity

- assets/react/v3/shared/utils/util.ts
Enhance error handling to provide a default message when the error response is incomplete.
> ✨ Refactor error handling in convertToErrorMessage function

- classes/Options_V2.php
https://app.clickup.com/t/86et2t3t7?comment=90180128694891
> Fix: php warning showing when resetting settings

- assets/react/v3/entries/import-export/components/History.tsx
- assets/react/v3/entries/import-export/components/Import.tsx
- assets/react/v3/entries/import-export/components/modals/ImportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Wrap the delete button in a div to enhance styling capabilities.
> 🆕 Refactor delete button for improved styling

- assets/react/v3/entries/coupon-details/components/coupon/CouponPreview.tsx
- assets/react/v3/shared/utils/currency.ts
- views/pages/ecommerce/coupon-list.php
Enhance the currency formatting logic and improve the display of coupon discounts for better clarity and consistency.
> ✨ Refactor currency and price formatting logic

- assets/react/v3/entries/import-export/components/Export.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/services/import-export.ts
Improve the export process by allowing support for exportable content, enabling more flexible data handling during exports.
> ✨ Enhance export functionality with exportable content support

- assets/react/v3/entries/import-export/components/App.tsx
- assets/react/v3/entries/import-export/components/History.tsx
Refactor the Main component loading to eliminate unnecessary suspense and improve performance. Update the History component to conditionally render based on loading state.
> ✨ Simplify Main component loading and enhance History component condition

- assets/react/v3/shared/molecules/Tabs.tsx
Improve active tab styles to ensure better visibility and accessibility during hover, focus, and active states.
Current: 
Expected:
> ✨ Enhance active tab styles for better accessibility

- assets/react/admin-dashboard/quiz-attempts.js
- assets/react/admin-dashboard/segments/filter.js
- classes/Instructors_List.php
- classes/Utils.php
- classes/Withdraw_Requests_List.php
- models/CourseModel.php
- v2-library/src/scss/components/_wp-dashboard-elements.scss
- views/elements/list-empty-state.php
- views/elements/list-navbar.php
- views/elements/navbar.php
- views/fragments/announcement-list.php
- views/pages/announcements.php
- views/pages/course-list.php
- views/pages/ecommerce/coupon-list.php
- views/pages/ecommerce/order-list.php
- views/pages/instructors.php
- views/pages/question_answer.php
- views/pages/quiz_attempts.php
- views/pages/students.php
- views/pages/withdraw_requests.php
- views/qna/qna-table.php
- views/quiz/attempt-table.php
1. Quiz attempt page
2. Withdraw requests page
3. Instructors page
> New filter design added

- assets/react/admin-dashboard/quiz-attempts.js
- cache/QuizAttempts.php
- classes/Q_And_A.php
- classes/Quiz_Attempts_List.php
- models/QuizModel.php
- views/fragments/announcement-list.php
- views/pages/question_answer.php
- views/qna/qna-table.php
- views/quiz/attempt-table.php
1. Extra space removed from before pagination
2. Q_And_A filter does not work fixed
3. Quiz attempts count after filter apply fixed
> List design issue fixes

- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicFooter.tsx
- assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/CollectionListTable.tsx
- assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/ContentListTable.tsx
- assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/index.tsx
- assets/react/v3/entries/course-builder/services/curriculum.ts
- assets/react/v3/shared/components/modals/ConfirmationModal.tsx
- assets/react/v3/shared/services/content-bank.ts
- assets/react/v3/shared/utils/endpoints.ts
- assets/react/v3/shared/utils/types.ts
1. Content bank content delete API integration added
2. Hide existing content from content modal
3. hide_empty added to collection API call
4. Button style improved
> Content bank updates 

- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
- assets/react/v3/entries/course-builder/components/curriculum/TopicFooter.tsx
- assets/react/v3/entries/course-builder/services/quiz.ts
- assets/react/v3/shared/config/constants.ts
- assets/react/v3/shared/utils/types.ts
Add Content Bank integration to the QuestionList and TopicFooter components, enabling users to access and add content from the Content Bank based on their subscription status.
> ✨ Integrate Content Bank functionality in QuestionList and TopicFooter components

- assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
- assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
Refactor the `handleCheckCorrectAnswer` function in both components to remove the unnecessary option parameter, improving code clarity and maintainability.
> 🛠️ Simplify handleCheckCorrectAnswer function in MultipleChoiceAndOrdering and TrueFalse components

- assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/ContentListTable.tsx
- assets/react/v3/shared/atoms/Select.tsx
- assets/react/v3/shared/atoms/TextInput.tsx
- assets/react/v3/shared/molecules/Table.tsx
Introduce a size prop to the Select and TextInput components for better customization. Update ContentListTable to conditionally render assignments based on addon availability.
> ✨ feat: add size prop to Select and TextInput components

- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
- assets/react/v3/shared/components/FocusTrap.tsx
- assets/react/v3/shared/components/Logo.tsx
Enhance question ID uniqueness by utilizing the existing question ID and add missing translator comments for better localization support.
> ✨ Update question ID generation and add translator comments

- assets/react/v3/entries/tax-settings/components/TaxSettings.tsx
Enhance the tax settings page by ensuring proper handling of undefined values for tax settings and improving the defaults for better user experience.
> 🛠️ fix(tax-settings): improve handling of undefined values and defaults

- assets/react/v3/shared/components/fields/quiz/questions/FormFillinTheBlanks.tsx
- assets/react/v3/shared/components/modals/ProIdentifierModal.tsx
- assets/react/v3/shared/utils/validation.ts
- eslint.config.mjs
- package-lock.json
- package.json
Refactor build scripts by removing unnecessary composer install and updating dependencies, including ESLint plugins and TypeScript versions.
> 🔧 Update build scripts and dependencies

- assets/react/v3/entries/import-export/components/modals/CollectionList/CollectionListTable.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
Simplify modal handling in `ExportInitialState`, streamline form value checks in `disableExportButton`, and enhance layout consistency with updated styles. Remove unused props for cleaner code.
> ✨ Refactor export modal and initial state handling

- assets/react/v3/entries/import-export/utils/utils.ts
Improve the hasAnyCourseWithChildren function to handle the course-bundle content type and enhance detection of children within courses.
> 🔧 Enhance hasAnyCourseWithChildren function for course-bundle support

- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
- assets/react/v3/entries/import-export/components/modals/import-export-states/ImportInitialState.tsx
- assets/react/v3/shared/services/import-export.ts
Enhance the exportable content functionality by allowing the inclusion of course_ids, simplifying the export initial state, and improving the condition for displaying the content bank based on addon status.
> ✨ Refactor exportable content handling with course_ids parameter

- assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
- assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
- assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
- assets/react/v3/entries/course-builder/utils/utils.ts
- assets/react/v3/shared/utils/quiz.ts
Update the quiz question validation logic to improve accuracy and consistency across components. Adjust imports to reflect the new validation utility location.
`Should be merged after v3.7.1`
> ✨ Refactor quiz question validation logic and imports

- assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
Integrate question conversion functionality into the QuestionList component and add comments for clarity.
> 🛠️ Integrate question conversion in QuestionList component

- package-lock.json
- package.json
Eliminate the unused dependencies: archiver and concurrently from the project.
> 🧹 Remove unused dependencies from package.json

- templates/dashboard/dashboard.php
Add tutor_before_dashboard_content hook to allow extending dashboard content
> feat(dashboard): add hook before dashboard content

- assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
- assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
Implement validation to ensure public courses cannot be paid and paid courses cannot be public in the CoursePricing and CourseSettings components.
> 🛠️ Fix course visibility validation based on pricing model

- helpers/QueryHelper.php
Previously, query helper methods required passing the full table name with the  `$wpdb->prefix`.
**Update**: now pass table names with or without the prefix — both will work seamlessly.
**Example**
Before
```php
global $wpdb;
QueryHelper::get_count( $wpdb->prefix . 'tutor_customer' )
```
Now
```php
QueryHelper::get_count( 'tutor_customer' )
// also support
QueryHelper::get_count( $wpdb->prefix . 'tutor_customer' )
```
> ⚡ Refactor: Allow query helper methods to be called without table prefix

- assets/react/v3/shared/components/subscription/PreviewItem.tsx
- assets/react/v3/shared/components/subscription/SubscriptionPreview.tsx
- assets/react/v3/shared/services/subscription.ts
Add `plan_order` to the subscription data structure and improve the `PreviewItem` component with a marquee effect and better hover interactions. Refactor the component for enhanced performance and clarify the usage of `plan_order` in the `SubscriptionPayload` type.
> ✨ Enhance subscription data structure and UI interactions

- assets/react/v3/entries/import-export/components/Export.tsx
- assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
- assets/react/v3/entries/import-export/components/modals/import-export-states/ImportExportCompletedState.tsx
- classes/Options_V2.php
Updated export flow to generate and download JSON files for non-Pro users, including dynamic file naming and size formatting. Adjusted UI to reflect file type and improved download button logic. Modified backend import to accept uploaded JSON files instead of POST data.
> fix: Enhance export/import to support JSON file handling
